server:
  servlet:
    port: 8080
    contextPath: /quora

spring:

  application:
    name: quora-api

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/Quora
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect