server:
  servlet:
    port: 8080
    contextPath: /api

spring:

  application:
    name: quora-api

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/mandeep
    username: postgres
    password: admin

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
